=== grin3671/gbf-relations/public/data/schemas/characters.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "id",
      "label",
      "group",
      "relations"
    ],
    "properties": {
      "id": {
        "type": ["integer", "string"],
        "description": "ID of character"
      },
      "label": {
        "type": "string",
        "description": "Character name"
      },
      "group": {
        "type": "string",
        "description": "Character group (e.g., d (default), a (astral), p (primal beast))",
        "pattern": "^[a-z]$",
        "maxLength": 1,
        "enum": [
          "d",
          "p",
          "a",
          "t"
        ]
      },
      "image": {
        "type": "string",
        "description": "Path to character image",
        "pattern": "^*\\.jpg$"
      },
      "faction": {
        "type": "string",
        "description": "Storyline group"
      },
      "relations": {
        "type": "array",
        "description": "List of relationships with other characters",
        "items": {
          "type": "object",
          "required": ["to"],
          "properties": {
            "to": {
              "type": ["integer", "string"],
              "description": "ID of related character"
            },
            "type": {
              "type": "string",
              "description": "Relationship type (append predetermined styles to lines)",
              "enum": [
                "crew",
                "action",
                "intention",
                "family",
                "parent",
                "ancestor",
                "distant-relatives",
                "co-worker",
                "teacher",
                "superior",
                "former-superior",
                "creator",
                "same-person",
                "clone",
                "belongs"
              ]
            },
            "title": {
              "type": "string",
              "description": "Relationship hint (e.g., Life Link)"
            },
            "arrows": {
              "type": "string",
              "description": "Relationship direction ('to' will draw an arrow near related character, 'from' - near current character)",
              "enum": ["to","from","from,to"]
            },
            "dashes": {
              "type": "boolean",
              "description": "Flag for special new relationship after game started (dashed line)"
            },
            "chapter": {
              "type": "string",
              "description": "Arc and Chapter number where the relationship appears (e.g., 1.36)"
            },
            "event": {
              "type": "string",
              "description": "Short name of the related event where this relation was revealed"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "additionalProperties": false
  }
}

=== grin3671/gbf-relations/public/data/characters.json
[
  {
    "id": 3990219000,
    "label": "Gran",
    "group": "d",
    "image": "./images/m/3990219000_01.jpg",
    "relations": [
      { "to": 3030005000, "type": "crew", "dashes": true, "chapter": "1.0" },
      { "to": 3030008000, "type": "crew", "dashes": true, "chapter": "1.4" },
      { "to": 3030006000, "type": "crew", "dashes": true, "chapter": "1.8" },
      { "to": 3030010000, "type": "crew", "dashes": true, "chapter": "1.14" },
      { "to": 3991612000, "title": "Friendship" }
    ]
  },
  {
    "id": 3050000000,
    "label": "Lyria",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3040643000_01.jpg",
    "relations": [
      { "to": 3990219000, "type": "action", "title": "Life Link", "dashes": true, "chapter": "1.0" }
    ]
  },
  {
    "id": 3050001000,
    "label": "Vyrn",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3050001000_01.jpg",
    "relations": [
      { "to": 3990219000, "chapter": "1.0" },
      { "to": 3993997000 }
    ]
  },
  {
    "id": 3030005000,
    "label": "Katalina",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3040054000_01.jpg",
    "relations": [
      { "to": 3050000000, "type": "action", "title": "Save", "chapter": "1.0" },
      { "to": 3040043000, "title": "Friendship" },
      { "to": 3020006000, "type": "former-superior", "chapter": "1.10" }
    ]
  },
  {
    "id": 3030006000,
    "label": "Io",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3040065000_01.jpg",
    "relations": [
      { "to": 3030010000, "dashes": true, "title": "Innermost Teaching" }
    ]
  },
  {
    "id": 3030007000,
    "label": "Eugen",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3040077000_01.jpg",
    "relations": [
      { "to": 3990002000, "type": "parent", "title": "Father" },
      { "to": 2040028000, "dashes": true, "title": "Innermost Teaching" }
    ]
  },
  {
    "id": 3030008000,
    "label": "Rackam",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3040059000_01.jpg",
    "relations": [
      { "to": 3030007000, "chapter": "1.9", "title": "Acquaintance" },
      { "to": 2040020000, "dashes": true, "title": "Innermost Teaching" }
    ]
  },
  {
    "id": 3030010000,
    "label": "Rosetta",
    "group": "p",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3040068000_01.jpg",
    "relations": [
      { "to": 3990003000, "type": "action", "dashes": true, "title": "Kidnapping", "chapter": "1.14" }
    ]
  },
  {
    "id": 3990000000,
    "label": "Sturm",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3040115000_01.jpg",
    "relations": [
      
    ]
  },
  {
    "id": 3990001000,
    "label": "Drang",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3040119000_01.jpg",
    "relations": [
      
    ]
  },
  {
    "id": 3993997000,
    "label": "Gallanth",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3993997000_01.jpg",
    "relations": [
      { "to": 3990219000, "type": "parent" },
      { "to": 3994001000, "type": "family" },
      { "to": 3040035000, "type": "action", "title": "Save" },
      { "to": 3040641000, "type": "crew" },
      { "to": 3030010000, "type": "crew" },
      { "to": 3992203000, "type": "crew" },
      { "to": 3030039000, "type": "crew" }
    ]
  },
  {
    "id": 3994001000,
    "label": "Rein",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3994001000_01.jpg",
    "relations": [
      { "to": 3990219000, "type": "parent" },
      { "to": 3993997000, "type": "family" },
      { "to": 3991123000, "type": "family" },
      { "to": 3994092000, "arrows": "to", "title": "Vessel" }
    ]
  },
  {
    "id": 3991123000,
    "label": "Partita",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3991123000_01.jpg",
    "relations": [
      
    ]
  },
  {
    "id": 3992591000,
    "label": "Omnipotent",
    "group": "d",
    "relations": [
      { "to": 2040003000, "type": "creator" },
      { "to": 3994086000, "type": "creator" },
      { "to": 3991292000, "type": "creator" },
      { "to": 3040251000, "type": "creator" },
      { "to": 3994000000, "type": "creator" }
    ]
  },
  {
    "id": 3994086000,
    "label": "Astralia\n[Astral God]",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3994086000_01.jpg",
    "relations": [
      
    ]
  },
  {
    "id": 2040003000,
    "label": "Bahamut\n[Sky God]",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/summon/m/2040003000.jpg",
    "relations": [
      { "to": 3994001000, "type": "action", "title": "Misson" },
      { "to": 3050001000, "type": "creator" },
      { "to": 3994092000, "type": "creator" }
    ]
  },
  {
    "id": 3040043000,
    "label": "Vira",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3040043000_01.jpg",
    "relations": [
      
    ]
  },
  {
    "id": 3991405000,
    "label": "Ares",
    "group": "a",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3991405000_01.jpg",
    "relations": [
      { "to": 3030005000, "type": "ancestor" }
    ]
  },
  {
    "id": 3020006000,
    "label": "Farrah",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3030037000_01.jpg",
    "faction": "Imperial Army",
    "relations": [
      { "to": 3030038000 }
    ]
  },
  {
    "id": 3030038000,
    "label": "Juri",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3040509000_01.jpg",
    "faction": "Imperial Army",
    "relations": [
      
    ]
  },
  {
    "id": 3990164000,
    "label": "Galston\n[Imperial Army Lieutenant]",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3990164000_01.jpg",
    "faction": "Imperial Army",
    "relations": [
      { "to": 3030038000, "type": "superior" }
    ]
  },
  {
    "id": 3990010000,
    "label": "Pommern\n[Imperial Army Captain]",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3990010000_01.jpg",
    "faction": "Imperial Army",
    "relations": [
      { "to": 3990164000, "type": "superior" },
      { "to": 3030005000, "type": "former-superior", "chapter": "1.0" }
    ]
  },
  {
    "id": 3990017000,
    "label": "Furias\n[Imperial Army Major General]",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3990017000_01.jpg",
    "faction": "Imperial Army",
    "relations": [
      { "to": 3990010000, "type": "superior", "chapter": "1.10" }
    ]
  },
  {
    "id": 3990251000,
    "label": "Gandharva\n[Imperial Army Lieutenant General]",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3990251000_01.jpg",
    "faction": "Imperial Army",
    "relations": [
      { "to": 3990017000, "type": "superior" }
    ]
  },
  {
    "id": 3990353000,
    "label": "Adam\n[Imperial Army General]",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3040432000_01.jpg",
    "faction": "Imperial Army",
    "relations": [
      { "to": 3990251000, "type": "superior" }
    ]
  },
  {
    "id": 3990153000,
    "label": "Freesia\n[Imperial Prime Minister]",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3990153000_01.jpg",
    "faction": "Erste Empire",
    "relations": [
      
    ]
  },
  {
    "id": 3990182000,
    "label": "Loki\n[Emperor of Erste]",
    "group": "a",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3990182000_01.jpg",
    "faction": "Erste Empire",
    "relations": [
      { "to": 3994088000, "type": "family" },
      { "to": 3990179000 }
    ]
  },
  {
    "id": 3994088000,
    "label": "Byleistr\n[Former Emperor of Erste]",
    "group": "a",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3994088000_01.jpg",
    "faction": "Erste Empire",
    "relations": [
      { "to": 3990153000, "type": "superior" },
      { "to": 3990353000, "type": "superior" },
      { "to": 3990510000, "type": "parent", "title": "Father" },
      { "to": 3991120000, "type": "co-worker", "event": "Anniv. 12" },
      { "to": 3994090000, "type": "co-worker", "event": "Anniv. 12" }
    ]
  },
  {
    "id": 3990510000,
    "label": "Orchis\n[Princess of Erste]",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3990510000_01.jpg",
    "faction": "Erste Empire",
    "relations": [
      { "to": 3990002000, "title": "Childhood Friend" }
    ]
  },
  {
    "id": 3990002000,
    "label": "Apollonia\n[Black Knight]",
    "group": "d",
    "image": "https://prd-game-a-granbluefantasy.akamaized.net/assets_en/img/sp/assets/npc/m/3040082000_01.jpg",
    "faction": "Erste Empire",
    "relations": [
      { "to": 3990000000, "type": "superior", "chapter": "1.3" },
      { "to": 3990001000, "type": "superior", "chapter": "1.3" },
      { "to": 3990003000 }
    ]
  },
  {
    "id": 3994090000,
    "label": "Lilith",
